from . import (
    person,
    patient,
    doctor,
    diagnosis,
    disease,
    disease_type,
    contact,
    doctor_visitor,
    personal_doctor_history,
    research,
    research_type,
    sample,
    schedule,
    # demo_model,
)
